import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import ConfirmDialog from '../components/ConfirmDialog';
import { LockIcon, SettingsIcon, LogOutIcon, UserIcon } from '../components/icons';
function Section({ eyebrow, title, children }) { return <section className="mb-7"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emberly-crimson-soft">{eyebrow}</p><h2 className="mt-1 font-display text-xl text-emberly-ivory">{title}</h2></div></div><div className="overflow-hidden rounded-2xl border border-emberly-ivory/10 bg-emberly-navy-deep/45">{children}</div></section>; }
function Row({ label, description, children }) { return <div className="flex items-center gap-4 border-b border-emberly-ivory/10 px-4 py-4 last:border-b-0 sm:px-5"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{label}</p>{description && <p className="mt-0.5 text-xs leading-5 text-emberly-ivory/50">{description}</p>}</div>{children}</div>; }
function Toggle({ checked, onChange, disabled }) { return <button type="button" disabled={disabled} onClick={() => onChange(!checked)} aria-pressed={checked} className={`relative h-6 w-11 shrink-0 rounded-full p-0.5 transition ${checked ? 'bg-emberly-crimson' : 'bg-emberly-ivory/15'} disabled:opacity-50`}><span className={`block h-5 w-5 rounded-full bg-emberly-ivory shadow transition-transform ${checked ? 'translate-x-5' : ''}`} /></button>; }
export default function Settings() {
  const { user, logout, updateUser } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate();
  const [isPrivate, setIsPrivate] = useState(user.isPrivate); const [savingPrivacy, setSavingPrivacy] = useState(false); const [pwOpen, setPwOpen] = useState(false); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [pwError, setPwError] = useState(''); const [pwSaving, setPwSaving] = useState(false); const [logoutConfirm, setLogoutConfirm] = useState(false);
  const togglePrivate = async (next) => { setIsPrivate(next); setSavingPrivacy(true); try { const r = await api.put('/users/me', { isPrivate: next }); updateUser({ isPrivate: r.data.user.isPrivate }); showToast(next ? 'Account is now private' : 'Account is now public'); } catch { setIsPrivate(!next); showToast('Could not update privacy setting', { tone: 'error' }); } finally { setSavingPrivacy(false); } };
  const changePassword = async (e) => { e.preventDefault(); setPwError(''); setPwSaving(true); try { await api.put('/users/me/password', { currentPassword, newPassword }); showToast('Password updated'); setPwOpen(false); setCurrentPassword(''); setNewPassword(''); } catch (err) { setPwError(err.response?.data?.error || 'Could not update password.'); } finally { setPwSaving(false); } };
  const field = 'w-full rounded-xl border border-emberly-ivory/12 bg-emberly-navy/55 px-3.5 py-3 text-sm text-emberly-ivory outline-none placeholder:text-emberly-ivory/35 focus:border-emberly-blue';
  return <div className="mx-auto w-full max-w-2xl px-4 py-5 sm:px-6 lg:py-10"><header className="mb-8"><div className="mb-3 grid h-11 w-11 place-items-center rounded-2xl bg-emberly-crimson text-emberly-ivory"><SettingsIcon className="h-5 w-5" /></div><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-emberly-crimson-soft">Your space</p><h1 className="mt-1 font-display text-3xl font-semibold">Settings</h1><p className="mt-1 text-sm text-emberly-ivory/50">Manage your account, privacy, and security.</p></header>
    <Section eyebrow="Account" title="Profile"><Row label="Username" description={`@${user.username}`}><span className="text-xs text-emberly-blue">Your identity</span></Row><Row label="Full name" description={user.fullName}><UserIcon className="h-4 w-4 text-emberly-blue" /></Row><Row label="Edit profile" description="Update your bio and display name"><button onClick={() => navigate(`/${user.username}`)} className="rounded-full border border-emberly-ivory/15 px-4 py-2 text-xs font-semibold transition hover:border-emberly-blue hover:text-emberly-blue">Edit</button></Row></Section>
    <Section eyebrow="Privacy" title="Who can see you"><Row label="Private account" description="Only approved followers can see your posts"><Toggle checked={isPrivate} disabled={savingPrivacy} onChange={togglePrivate} /></Row></Section>
    <Section eyebrow="Security" title="Keep your account safe">{!pwOpen ? <Row label="Password" description="Change the password you use to sign in"><button onClick={() => setPwOpen(true)} className="flex items-center gap-1.5 rounded-full border border-emberly-ivory/15 px-4 py-2 text-xs font-semibold transition hover:border-emberly-blue hover:text-emberly-blue"><LockIcon className="h-3.5 w-3.5" />Change</button></Row> : <form onSubmit={changePassword} className="space-y-3 p-4 sm:p-5"><div className="flex items-center gap-2 text-xs text-emberly-blue"><LockIcon className="h-4 w-4" />Use at least 8 characters for your new password.</div><input className={field} type="password" required value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} placeholder="Current password" /><input className={field} type="password" required minLength={8} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="New password" />{pwError && <p className="text-sm text-emberly-crimson-soft" role="alert">{pwError}</p>}<div className="flex gap-2"><button disabled={pwSaving} className="flex-1 rounded-full bg-emberly-crimson px-4 py-2.5 text-sm font-semibold transition hover:bg-emberly-crimson-dark disabled:opacity-50">{pwSaving ? 'Saving…' : 'Save password'}</button><button type="button" onClick={() => { setPwOpen(false); setPwError(''); }} className="rounded-full border border-emberly-ivory/15 px-4 py-2.5 text-sm">Cancel</button></div></form>}</Section>
    <button onClick={() => setLogoutConfirm(true)} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-emberly-crimson/30 bg-emberly-crimson/8 py-3.5 text-sm font-semibold text-emberly-crimson-soft transition hover:bg-emberly-crimson/15"><LogOutIcon className="h-4 w-4" />Log out</button>
    <ConfirmDialog open={logoutConfirm} title="Log out of Emberly?" confirmLabel="Log out" onConfirm={logout} onCancel={() => setLogoutConfirm(false)} />
  </div>;
}
